name: Updater

on:
    workflow_dispatch:
    schedule:
        - cron: "0 12 * * *" # Runs at 12:00 UTC everyday

jobs:
    generate_lists:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo content
              uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

            - name: Install Python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Update EMA blocklist
              run: python parsers/ema.py

            - name: Update NKRZI blocklist
              run: python parsers/nkrzi.py

            - name: Update NKRZI IP blocklist
              run: python parsers/nkrzi_ip.py

            - name: Update RNBO blocklist
              run: python parsers/rnbo.py

            - name: Update RNBO IP blocklist
              run: python parsers/rnbo_ip.py

            - name: Commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A
                  git diff --name-only --cached --exit-code || ( git commit -am "🔁 Update blocklists" && git push )
